ALTER TABLE provider_configs
    ADD COLUMN channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE provider_configs
    ADD CONSTRAINT provider_configs_channel_id_key UNIQUE (channel_id);

-- These were the pre-release catalog rows. A new installation starts with no
-- channels; preserve any row that has already been configured with a key.
DELETE FROM provider_configs
WHERE id IN (
    '10000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000002',
    '10000000-0000-4000-8000-000000000003'
)
AND api_key_ciphertext = '';

DELETE FROM settings
WHERE key = 'default_catalog_initialized';
